### ISSUE TITLE
Breadcrumbs should be optional

### ISSUE THREAD

**Issue by kanarb** [knice/ucsc-drupal#11]
We need a theme setting that allows breadcrumbs to be toggled on and off. Since the library defines its structure using taxonomy, the breadcrumbs don't match the URL. this makes breadcrumbs more confusing than useful.

**Comment by knice** [comment]
Add theme option for toggling breadcrumbs on and off because frequently, breadcrumbs do not match the actual path in the URL.

**Comment by knice** [comment]
Library uses crumbs. Unless we get a request for this specifically, we'll leave the theme as it is for now.
