### ISSUE TITLE
styles for images in the #content area

### ISSUE THREAD

**Issue by kanarb** [knice/ucsc-drupal#23]
The old ucscv2 theme has the following. We'll need something similar, though perhaps with a different background color.
# content img {

```
background-color: #F9F8F2;
margin: 10px;
padding: 4px;
```

}

**Comment by kanarb** [comment]
I added the styles, but I'm not sure the color is right.

**Comment by knice** [comment]
I can take a look at them and finalize the colors based on the WCMS styles.

**Comment by knice** [comment]
I've cleaned up the styles to match the WCMS image styles as closely as possible.

![images](https://cloud.githubusercontent.com/assets/36719/9069858/bc17b2bc-3aa0-11e5-8e7c-08eb628b806f.jpg)
