### ISSUE TITLE
Should page title be wider?

### ISSUE THREAD

**Issue by kanarb** [knice/ucsc-drupal#24]
Here's an example of a page where it looks like the page title should be wider. Perhaps this rule should be changed:

.page_title {
    width: 70%;
}

**Comment by knice** [comment]
Has to do with secondary logos. I'll test this feature, but let's assume it needs to stay in for now.

**Comment by kanarb** [comment]
Wonder if we could structure the rule so title are shorter only when a secondary logo is present.
