### ISSUE TITLE
Image captions should allow text wrap

### ISSUE THREAD

**Issue by kanarb** [knice/ucsc-drupal#26]
Here's an example of problems caused by non-wrapping image caption:
https://website.library.ucsc.edu/reg-hist/louis-f-fackler-founding-campus-engineer-uc-santa-cruz

**Comment by knice** [comment]
If you add these styles to your custom stylesheet (and modify the `margin` and `float` for right floating images), that will fix this issue.

![content-images](https://cloud.githubusercontent.com/assets/36719/9069372/c2eb892c-3a9d-11e5-8f31-bd16b57779b7.jpg)

**Comment by kanarb** [comment]
This fix works for us.
